server:
  port: 6066



spring:
  profiles:
    active: dev
---

spring:
  application:
    name: configserver6061
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

---

spring:
  application:
    name: configserver6062
  profiles: pro

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/
